### ISSUE TITLE
URGENT - Plugin Cannot be installed in Intel XDK Android Build

### ISSUE THREAD

**Issue by writeosahon** [01org/AppSecurityApi#1]
Hello @mshaver @argretzi @nadavnesher @OhadBoimelIntel @DennisFilimonovIntel . Please, I've been using this plugin for about 1 month in my Intel XDK Android Cordova Build without any issues. I last used it on the 17th September 2015. Everything worked fine.

However, I tried to rebuild my project today 20th September and the build fails. I just get a single error message from Intel XDK saying that the Security plugin could not be installed. there are no further error messages.
I have used this plugin to build very important security features into my app. Please can you urgently investigate the reason behind the plugin build failure.
I am using Cordova CLI 4.1.2 and building an Android project.

Thank you

**Comment by OhadBoimelIntel** [comment]
Hi Osahon,

I am happy to here that you are using the App Security API plugin.

I also see that Intel XDK build system fails to build Android app that includes App Security API plugin, I have raised the issue to Intel XDK team, I will keep you posted.

Thank Ohad

**Comment by writeosahon** [comment]
Hello Ohad.
Thanks for responding.

Alot of people use your Security Plugin, you don't get any issues report because the plugin is flawless :-)

Thanks for helping to report the issue to Intel XDK, I need to rebuild my project by Tuesday. I'll wait for any updates

Thanks
Osahon Okungbowa
Sent from my Windows Phone

-----Original Message-----

**Comment by writeosahon** [comment]
Hello @OhadBoimelIntel . 
I just tried to build again today (Monday). the build still fails.
Please any news from the IntelXDK team regarding this.

Thanks for your help

**Comment by OhadBoimelIntel** [comment]
Hi Osahon,

Thank you for the warm feedback, 
The issue was a bad-configuration in the XDK build system, it was fixed.
I am able to build App with the plugin using the XDK, please try again and let me know.

Thank, 
Ohad

**Comment by writeosahon** [comment]
hello @OhadBoimelIntel .
the problem has NOT been fixed. I just tried to build my app with the plugin and it failed. When I removed the plugin, the build is successful. 
I attached a screenshot of my build failure. The security api is marked in red with a message - "failed to install plugin".
This is very frustrating, because the plugin was working very fine until 2 days ago.
Please, I am supposed to have an update of my app ready by tomorrow, can the XDK team fix this today?
![build_screenshot](https://cloud.githubusercontent.com/assets/6549065/9993768/547a691e-6071-11e5-8839-a13bba4a2571.png)

**Comment by OhadBoimelIntel** [comment]
Hi Osahon,

I am unable reproduce the failure, empty project with App Security API plugin builds just fine.
Can you please try the following?
1.  Create a new empty project
2.  Add App Security API plugin  build  see if passes
3.  Add other plugin (that your app uses)  build  see if passes
4.  Continue step 3 till you see failure

The failure is probably with the first plugin that has conflict with the App Security API plugin.
Please reply with the outcome.

Thanks, 
Ohad

**Comment by writeosahon** [comment]
Hello @OhadBoimelIntel .
Sorry, I haven't replied on time, I was feeling a little ill.
I have confirmed that the App Security API plugin is working well with the latest release of XDK (version 2496).

Thanks again for all your assistance; Also thank your entire team for creating such an important plugin that works great.

Regards,
Osahon

**Comment by OhadBoimelIntel** [comment]
Hi @writeosahon, 

I am happy to hear that it works for you, I have closed the issue.

If it's OK, I would like to get your feedback regarding the App Security API plugin, I appreciate if you can send me an email to ohad.boimel@intel.com so I will be able to reply with some questions of how to improve our offering.

Thanks, 
    Ohad
