### ISSUE TITLE
iOS: Bitcode support

### ISSUE THREAD

**Issue by zarko-tg** [01org/AppSecurityApi#7]
It seems that you don't support Bitcode and building an app with it enabled naturally fails.
Any plan to support it in near future?

**Comment by OhadBoimelIntel** [comment]
HI @zarko-tg,

Thank you for reporting the issue!
We did an analysis and it looks like that external libraries that we use are compiled with no Bitcode support.
Hopefully will be fixed in next version.

Thank, 
Ohad

**Comment by OhadBoimelIntel** [comment]
Hi @zarko-tg ,

Just wanted to update you that we are working to add the Bitcode support into our next version.

Thank, Ohad

**Comment by zarko-tg** [comment]
Hi @OhadBoimelIntel, I appreciate the update. Thank you

**Comment by DanSIntel** [comment]
Hi @zarko-tg 
App Security API supports bitcode optimization for iOS apps from v1.4.1.
We published the release candidate of v1.4.1 today and we'll be more than happy to know if it solves the issue you have seen.

Thanks,
Dan.

**Comment by zarko-tg** [comment]
Thanks @DanShmulIntel, I'll be on the ball soon.
