### ISSUE TITLE
sendRequest method will return 13 error code( Policy violation detected)

### ISSUE THREAD

**Issue by zhuyongyong** [01org/AppSecurityApi#9]
Use the Example on https://software.intel.com/en-us/node/564382 to check sendRequest  method,
The requestFormat is "JSON", and the Format of secureDataDescriptors is "SECURE_DATA_PLAINTEXT_UNDECORATED", but this case will fail, the error message is
"code = 13, message = Policy violation detected expected true got false"

**Comment by OhadBoimelIntel** [comment]
HI @zhuyongyong,

Thank you for the issue report, do you see the issue in crosswalk for windows extension?
Can you please provide the test code so we will easily reproduce it?

**Comment by zhuyongyong** [comment]
You can see the case code on https://github.com/zhuyongyong/crosswalk-test-suite/blob/Appsecurity/supportWindows/webapi/webapi-appsecurity-external-tests/appsecurityapi/AppSecurityApi_sendRequest_JSON_PLAINTEXT.html

This error can alse reproduced on android platform.

**Comment by OhadBoimelIntel** [comment]
Hi @zhuyongyong,

The above link is broken, can you please provide a new one?

**Comment by zhuyongyong** [comment]
This case has been merged to 
https://github.com/crosswalk-project/crosswalk-test-suite/blob/master/webapi/webapi-appsecurity-external-tests/appsecurityapi/AppSecurityApi_sendRequest_JSON_PLAINTEXT.html

**Comment by AlonPludaIntel** [comment]
Hi  @zhuyongyong,
First, thanks a lot for the issue report. we are happy to provide information and fix potential problem on our product.
For the issue itself:
The problem was wrong usage of the API functions.
When using the “Send” method with Descriptors, note that the InstanceID of the descriptor, must have The URL as “WebOwner”.
**You can find it in our sample:**
https://software.intel.com/en-us/node/604524 

**In your case, all you need to do is change line 109 from:**
{'data': 'plaintext data',}
to:
{'data': 'plaintext data' , 'webOwners': ["crosswalk-project.org"]}

so your "test" function sould look like this: 

function test() {
  async_test(function(t) {
    try{
      intel.security.secureData.createFromData(
        function(instanceID) {
          intel.security.secureStorage.write(
            function() {
              intel.security.secureStorage.read(
                function(passwordSecureDataInstanceID) {
                  intel.security.secureTransport.open(
                    function(secureTransportInstanceID){
                      var request = {'username':'John Smith', 'password':''};
                      var requestDescriptors = [{'Location': 'body', 'Path': 'password', 'Type': 'String', 'InstanceID': passwordSecureDataInstanceID, 'Format': 'SECURE_DATA_PLAINTEXT_UNDECORATED'}];
                      intel.security.secureTransport.sendRequest(
                        function(response){
                          t.step(function() {
                            assert_not_equals(response.responseBody, null);
                          });
                          t.done();
                        },
                        function(errorObj){
                          t.step(function() {
                            assert_true(false, 'fail: code = ' + errorObj.code + ', message = ' + errorObj.message);
                          });
                          t.done();
                        },
                        {'instanceID':secureTransportInstanceID, 'requestBody':JSON.stringify(request), 'requestFormat':'JSON', 'secureDataDescriptors':requestDescriptors}
                      );
                    },
                    function(errorObj){
                      t.step(function() {
                        assert_true(false, 'fail: code = ' + errorObj.code + ', message = ' + errorObj.message);
                      });
                      t.done();
                    },
                    {'url': 'https://crosswalk-project.org', 'method':'PUT'}
                  );
                },
                function(errorObj) {
                  t.step(function() {
                    assert_true(false, 'fail: code = ' + errorObj.code + ', message = ' + errorObj.message);
                  });
                  t.done();
                },
                {'id': 'id1'}
              );
            },
            function(errorObj) {
              t.step(function() {
                assert_true(false, 'fail: code = ' + errorObj.code + ', message = ' + errorObj.message);
              });
              t.done();
            },
            {'id': 'id1', 'instanceID': instanceID}
          );
        },
        function(errorObj) {
          t.step(function() {
            assert_true(false, 'fail: code = ' + errorObj.code + ', message = ' + errorObj.message);
          });
          t.done();
        },
        {'data': 'plaintext data' , 'webOwners': ["crosswalk-project.org"]}
      );
    } catch (e) {
      assert_true(false, "Exception: {" + e.message + "}");
    }
  }, document.title);
}

If you encounter any further issues, you welcome to contact us again.
Thanks,
Alon
